

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author pedrto
 */
public class Pabout extends javax.swing.JPanel {

    /**
     * Creates new form Pabout
     */
    public Pabout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_1 = new javax.swing.JPanel();
        imglibro = new javax.swing.JLabel();
        carnettxt = new javax.swing.JLabel();
        nametxt = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(930, 560));

        P_1.setBackground(new java.awt.Color(255, 255, 255));
        P_1.setPreferredSize(new java.awt.Dimension(930, 560));
        P_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imglibro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imglibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/libroinf.jpg"))); // NOI18N
        P_1.add(imglibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 370));

        carnettxt.setFont(new java.awt.Font("Roboto Medium", 2, 24)); // NOI18N
        carnettxt.setForeground(new java.awt.Color(6, 5, 18));
        carnettxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carnettxt.setText("Carnet: 202100953");
        P_1.add(carnettxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 930, 40));

        nametxt.setFont(new java.awt.Font("Roboto Medium", 2, 24)); // NOI18N
        nametxt.setForeground(new java.awt.Color(6, 5, 18));
        nametxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nametxt.setText(" Nombre: Damaris Julizza Muralles Véliz");
        P_1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 930, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel P_1;
    private javax.swing.JLabel carnettxt;
    private javax.swing.JLabel imglibro;
    private javax.swing.JLabel nametxt;
    // End of variables declaration//GEN-END:variables
}
