

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author pedrto
 */
public class Pprincipal extends javax.swing.JPanel {

    /**
     * Creates new form Pprincipal
     */
    public Pprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        P_1 = new javax.swing.JPanel();
        L_logousac = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(930, 560));

        P_1.setBackground(new java.awt.Color(255, 255, 255));
        P_1.setMinimumSize(new java.awt.Dimension(930, 560));
        P_1.setPreferredSize(new java.awt.Dimension(930, 560));
        P_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L_logousac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_logousac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-universidad-de-san-carlos-de-guatemala.png"))); // NOI18N
        P_1.add(L_logousac, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 930, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_logousac;
    private javax.swing.JPanel P_1;
    // End of variables declaration//GEN-END:variables
}
